version: '3.7'

services:

 orders:
   build:
     context: ./services/orders
     dockerfile: Dockerfile-dev
   volumes:
     - './services/orders:/usr/src/app'
   ports:
     - 6001:5000
   environment:
     # - FLASK_APP=project/__init__.py
     - FLASK_ENV=development
     - APP_SETTINGS=project.config.DevelopmentConfig  # nuevo
     - DATABASE_URL=postgres://postgres:postgres@orders-db:5432/orders_dev  # nuevo
     - DATABASE_TEST_URL=postgres://postgres:postgres@orders-db:5432/orders_test  # nuevo
   depends_on:  # nuevo
     - orders-db

 orders-db:  # nuevo
   build:
     context: ./services/orders/project/db
     dockerfile: Dockerfile
   ports:
      - 5436:5432
   environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres